### ISSUE TITLE
Strange behavior for TestOEM on Ubuntu 20.04

### ISSUE THREAD

**Issue by riclarsson** [atmtools/arts#168]
**Describe the bug**
Cannot run through TestOEM in accepted build configuration.

**To Reproduce**
Install ubuntu 20.04 or upgrade to ubuntu 20.04.  Install dependencies.  "make check"

**Expected behavior**
Works within reasonable time.

**System info (please complete the following information):**
 - OS: Ubuntu 20.04 base
 - Version: Latest

**Additional context**
Switching to libopenblas from liblapack3 and libblas3 made the code run.  (Thanks Oliver!)

**Suggested solution**
Check for liblapack3 and libblas3 and give appropriate warning.  (I am not good enough at cmake to make this check)

**Comment by olemke** [comment]
I cannot reproduce this on Ubuntu 20.04. Tried in Release and RelWithDebInfo mode. This issue seems to depend on other factors than just the Ubuntu version (maybe CPU type).
However, on my testing, the TestOEM performed twice as fast with OpenBLAS compared to LAPACK/BLAS. Therefore I placed replaced LAPACK/BLAS with OpenBLAS in our dependency list in README.md and on the "Getting ARTS" webpage.
cmake will now output a warning on Linux saying that we recommend OpenBLAS if any other LAPACK implementation is detected. On macOS, LAPACK is provided by Apple's own Accelerate framework which is a good default choice on that OS.
