### ISSUE TITLE
SCATMECH

### ISSUE THREAD

**Issue by erikssonpatrick** [atmtools/arts#217]
Richard found an interesting C++ library:

https://github.com/usnistgov/SCATMECH

The library could be useful in several ways. It would give us Mie and Rayleigh code. It also contains T-matrix (seems to be well documented) that potentially could free us from the fortran T-matrix code. In a longer perspective, it seems very useful for setting up models for the surface. 

Not urgent now, but Oliver please take a look. Are there any showstoppers?

**Comment by riclarsson** [comment]
Patrick, I had a few minutes before the end of the day here.  To do this linking, if you want to use it, here is a scheme.

Put SCATMECH in 3rdparty/ --- this should be what you get when you download the code as a zip from github.  Rename the folder to SCATMECH instead of SCATMECH-master.

Add this to 3rdparty/CMakeLists.txt:
```cmake
add_subdirectory(SCATMECH)
```

Add this as 3rdparty/SCATMECH/CMakeLists.txt
```cmake
add_subdirectory(code)
```

Add this as 3rdparty/SCATMECH/code/CMakeLists.txt:
```cmake
project(SCATMECH CXX)

file (GLOB SCATMECH_HEADERFILES "${CMAKE_CURRENT_SOURCE_DIR}/*.h")
file (GLOB SCATMECH_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp")

add_library(scatmech STATIC ${SCATMECH_HEADERFILES} ${SCATMECH_SOURCES})
set_target_properties(scatmech PROPERTIES LINKER_LANGUAGE CXX)
target_compile_options(scatmech PRIVATE -Wno-deprecated-declarations -Wno-maybe-uninitialized -Wno-shadow -Wno-reorder -Wno-conversion -Wno-unused-parameter -Wno-deprecated-copy -Wno-unused-variable -Wno-sign-compare -Wno-unused-function -Wno-unused-but-set-variable -Wno-parentheses -Wno-catch-value)
```

You can now compile SCATMECH without warnings.  It has a lot of warnings, so I would be a bit careful when looking at using it.

Add this to src/CMakeLists.txt:
```cmake
########################################################################################
# SCATMECH interface in ARTS
add_library(scatmech_interface STATIC scatmech_interface.cc)
target_link_libraries(scatmech_interface PRIVATE scatmech)
target_link_libraries(scatmech_interface PUBLIC matpack)
target_include_directories(scatmech_interface PRIVATE ${SCATMECH_SOURCE_DIR})
list (APPEND ALL_ARTS_LIBRARIES scatmech_interface)
########################################################################################
```

Add this as src/scatmech_interface.cc:
```cpp
#include <allrough.h>
#include <askuser.h>
#include <axifree.h>
#include <axipart.h>
#include <bobvlieg.h>
#include <brdf.h>
#include <coatedmie.h>
#include <crossgrating.h>
#include <crossgrating2.h>
#include <crossrcw.h>
#include <crough.h>
#include <dielfunc.h>
#include <diffuse.h>
#include <facet.h>
#include <fft.h>
#include <filmtran.h>
#include <finiteaperture.h>
#include <firstdiffuse.h>
#include <flake.h>
#include <focussedbeam.h>
#include <fresnel.h>
#include <gcross.h>
#include <grating.h>
#include <inherit.h>
#include <instrument.h>
#include <lambert.h>
#include <local.h>
#include <matrix3d.h>
#include <matrixmath.h>
#include <miescat.h>
#include <mueller.h>
#include <nsphere.h>
#include <oasphere.h>
#include <onelayer.h>
#include <optconst.h>
#include <phasefunction.h>
#include <polydisperse.h>
#include <random.h>
#include <raygscat.h>
#include <rayinst.h>
#include <rayscat.h>
#include <raystack.h>
#include <rcw.h>
#include <reflectance.h>
#include <rough.h>
#include <roughnes.h>
#include <scateval.h>
#include <scatmatrix.h>
#include <scatmech.h>
#include <scattabl.h>
#include <sizedistribution.h>
#include <sphdfct.h>
#include <sphprt.h>
#include <sphrscat.h>
#include <subbobvlieg.h>
#include <subsphere.h>
#include <tmatrix.h>
#include <torrspar.h>
#include <transmit.h>
#include <two_source.h>
#include <twoface.h>
#include <urough.h>
#include <vector3d.h>
#include <zernike.h>
#include <zernikeexpansion.h>

#include "scatmech_interface.h"

void get_output(Numeric& val) {
  // use something (preferably more than this)
  SCATMECH::RayleighScatterer a{};
  val = a.get_lambda();
}
```

And lastly, add this as src/scatmech_interface.h:
```cpp
#ifndef scatmech_interface_h
#define scatmech_interface_h

#include "matpackI.h"

void get_output(Numeric& val);

#endif  // scatmech_interface_h
```

You can now do `#include "scatmech_interface.h"` from anywhere in ARTS standard.  There should be no name collisions with the rest of ARTS as I understand it.  Inside scatmech_interface.h you can define your interface to SCATMECH.  I have made it so you can pass all matpack types over this border, as input and output.  You might want to increase the matpack header-count.  In scatmech_interface.cc, you have access to the entire SCATMECH namespace with all of the functions you might want.  I do not know how to use these, so I have not tried to make any sense of it.  I just did the above and tried `#include "scatmech_interface.h"` in zeeman.cc and it compiles properly.  I also do not know if it would make more sense to just access parts of the interface.  Someone willing to work with this should look at that, this is just CMake linking.

**Comment by erikssonpatrick** [comment]
@riclarsson Thanks for testing this. 

@simonpf FYI if there happen to be stuff in SCATMECH of interest for you. 

This was just a basic question from me. I don't have any time to explore SCATMECH now. For now I have more urgent things. So from my side this is enough to close the issue.

**Comment by olemke** [comment]
@riclarsson Thanks for checking this out.

So, yes, if there is a need for this, we could integrate it into ARTS. License looks fine too.

**Comment by erikssonpatrick** [comment]
For me this was just a question for the moment. And the answer seems to be yes. There seems to be no immediate need of SCATMECH and I close the issue.
