### ISSUE TITLE
Second order integration

### ISSUE THREAD

**Issue by erikssonpatrick** [atmtools/arts#258]
@riclarsson I made a test with the latest version of second order integration in iyEmissionStandard. I got basically identical results with first and second order integration. I assume this means that the max criterion has the result that the algorithm falls back to first order more or less for each RT step. Maybe this is what you meant in some comment you made. Anyhow, as it is now second order ends up pretty much useless as it does not improve accuracy, but still use more calculations.

But was it really necessary to introduce the max criterion? My memory is that the large deviation for y I reported about did not involve I, but the later Stokes elements. Maybe my memory is wrong, but maybe there was just a problem for higher stokes_dim and polarised situations?

**Comment by erikssonpatrick** [comment]
With the comment above I wanted to give the input I can provide. For the coming weeks, I will have no free time at all and must all non-urgent things to the side. 

@m-brath I added you here as you have looked at the second order integration algorith most carefully among us. Could you try to help Richard? What do you say, is the max criterion necessary for clear sky (where maybe the absorption can vary strongly ver a RT step, but not the Planck function)? How should the expression be implemented for stokes_dim > 1?

**Comment by riclarsson** [comment]
There was a problem for all Stokes dimensions in the test case you sent me.  We don't have the propagation matrix in this part of the calculations, so the max-condition must always be active to not encounter this issue.

As I have told you, we would have to change the RT setup to fix this, so that the "update_radiation_vector" function takes the propagation matrix too to test the limit.  This means its derivative and the distance plus its derivatives should also be sent in.

But before I will touch the code to do this, I need a full derivation of the second order source terms.  Because it is very strange to me that such a limit can at all be required.  The presented equation clearly allows for it this to happen but the image they show of the problem does not allow for this to happen.  I don't have the time for this derivation myself for the near future, but I won't touch the code before I have it.

**Comment by m-brath** [comment]
> @m-brath I added you here as you have looked at the second order integration algorith most carefully among us. Could you try to help Richard? What do you say, is the max criterion necessary for clear sky (where maybe the absorption can vary strongly ver a RT step, but not the Planck function)? How should the expression be implemented for stokes_dim > 1?

I think for a pure clear sky atmosphere on earth the max criterion is mostly not needed, because the temperature and the absorption gradients over one rt step are mostly not strong enough. Nonetheless I would incorporate the max criterion within the solver. As I could not understand it from the code, how do you exactly define the max criterion?  For higher stokes dim, I have no answer yet. I have to think and read about it.

**Comment by riclarsson** [comment]
@erikssonpatrick Please tell me what remains to be done to close this.  As we left it, I feel I have done my part but I cannot remember if anything is missing.

**Comment by erikssonpatrick** [comment]
Answer by email to include Vasileios

**Comment by riclarsson** [comment]
No more information so this is now closed.
