### ISSUE TITLE
arts-xml-data/spectroscopy

### ISSUE THREAD

**Issue by stefanbuehler** [atmtools/arts#294]
@riclarsson: Could we rename arts-xml-data/spectroscopy/cat to artscat?
(Or perhaps add this to some todo list to change the next time the catalog is updated.)

Also, more general question to all:

Could we introduce a policy that there should be a readme.txt file in at least the higher-level directories of arts-xml-data, with at least one sentence on what  the contents are? (What triggered this is that I was again confused on the meaning of the cat versus the HITRAN directory.)

Suggested content for arts-xml-data/spectroscopy/readme.txt

Subdirectories contain:

Hitran:        Original HITRAN catalog (FIXME date of download)
PartitionSums: Partition function data (TIPS)
Perrin:        Perrin catalog (species-dependent broadening, but only up to 2.5 THz, legacy format) 
Perrin_newformat_speciessplit: Same as above in current arts format
cat:           ARTS line catalog, based on the HITRAN version above, with some adjustments.
cia:           Collision-induced absorption data
nlte:          Data for non-LTE calculations
zeeman:        Zeeman splitting data

**Comment by riclarsson** [comment]
We can rename cat.  I would like this to happen on your side though.  I suspect it would be a good idea to somehow purge the existence of cat, since I don't remember subversion having good version control options for renaming.  We can also remove either Perrin or Perring_newformat.  I think perhaps only the former should remain.  There is still a lot missing from the parsing of these files, things no one ever got around to fixing (quantum number parsing).  So the latter lacks a lot of tags, making it impossible to use with many new features in ARTS (and the former can also not do these things since it still lacks parsing).

I like the enforced policy of readmes.
