### ISSUE TITLE
Planetary tests fail due to missing iso ratio for new CO2-737

### ISSUE THREAD

**Issue by olemke** [atmtools/arts#326]
**Describe the bug**
We recently added the new isotopologue CO2-737 to species data. The planetary tests now fail, because this isotopologue is not available in the input files provided in `arts-xml-data`:

```
arts-xml-data/planets/Jupiter/isotopratio_Jupiter.xml
arts-xml-data/planets/Mars/isotopratio_Mars.xml
arts-xml-data/planets/Venus/isotopratio_Venus.xml
```

**To Reproduce**
Run the planetary surface tests in your build directory:
```
ctest -E python -R arts.ctlfile.xmldata.artscomponents.arts-xml-data.TestSurf
```
In the current master, this triggers an assertion, but with the fix in PR #325, you'll get:
```
Run-time error in controlfile: /Users/olemke/Hacking/uhh/arts/controlfiles/artscomponents/arts-xml-data/TestSurf_Venus.arts
Run-time error in method: lbl_checkedCalc
User Error: isoratios.getParam(sp, iso).nelem() == 0
Error is found at:
        /Users/olemke/Hacking/uhh/arts/src/absorption.cc:333
Please follow these instructions to correct your error:
No isotopologue ratio found for CO2-737
```

The question is what is the correct way to approach a fix here. Even if we add the appropriate isotopologue ratios to those files, the planetary tests are using the Perrin catalogue, which doesn't provide any CO2-737 lines anyway.

**Comment by riclarsson** [comment]
I think your solution is good enough.  Combine this with limiting the planetary test to things it can have known about on creation.

The planetary tests are clearly poorly designed to not work in case a new molecule is added.  To support all molecules is a goal not a demand.  We should not stop adding things for Earth just because it doesn't work yet on other planets.

That said, it does present a bit of a greater problem with the general design of the isotopologues:  In cases where the ratio is unknown, you have to hope that there's no other molecule partly named CO2 that influences the spectra around your target CO2 molecule.  If there is, then you cannot perform reliable forward calculations.

**Comment by riclarsson** [comment]
#354 and updates to arts-xml-data closes this
