### ISSUE TITLE
ppvar_trans_partial

### ISSUE THREAD

**Issue by erikssonpatrick** [atmtools/arts#352]
The documentation says that this is the transmissivity between ppath points. If np is the number of such points, there should be np-1 transmissivities, but there are np ones. So either the documentation is wrong or the implementation is wrong.
I would say that the implementation should be changed to follow the documentation. 
If I am informed about what the present values are, I could fix this.

**Comment by riclarsson** [comment]
You are definitely wrong here Patrick.   The documentation states that its supposed to be ppath.np large.  You can see this at: https://atmtools.github.io/arts-docs-master/docserver/variables/ppvar_trans_partial.html

If you wish to change the documentation and the behavior, here's all the information you need:

Reduce the size by one in m_rte.cc at line 264.

I would advise against doing this in isolation, though, since it just complicates things needlessly to have so many similarly named variables with different sizes.  The variable name should be changed to have the prefix `rtvar_` instead of `ppvar_`, and the same set of changes should apply to all three of `ppvar_trans_cumulat`, `ppvar_trans_partial`, and `ppvar_iy`.

**Comment by erikssonpatrick** [comment]
I referred to the documentation text. Yes, I noticed the size, but skipped that to stay brief and it felt secondary. 

I am not sure the fix is that easy. On lines 263-264  ppvar_trans_cumulat and  ppvar_trans_partial are resized, getting size np in the dimension of concern. On lines 565-566 they are both filled in the same loop. Here I assume that lvl_rad.nelem() is np, otherwise  ppvar_trans_cumulat and  ppvar_trans_partial are not fully filled today and crap values can appear. 
I assume all is OK for ppvar_trans_cumulat. But if the variable ppvar_trans_partial shall make sense, there must be one value less, or we have to be clear about the "extra" value. For example, does it correspond to the distance between the last ppath point and the sensor (that can be >=0) and is always 1?
The while things boils down to what is in lyr_tra? It seems to have np levels/layers? How are they defined? If you inform me about that, the rest should be clear for me to fix.

I don't see how this is relevant for the naming of the variable(s). The logic for me is that these variables are defined along the path. Maybe not perfect naming, but switching to rtvar would not help at all in my view. Rather add confusion.

**Comment by riclarsson** [comment]
If it tracks `ppath`, it should be `ppath.np` long.  The meaning of the values in the variable is thus "to the next level" and not "through this layer". If you want to output layer variables, they should be named appropriately, otherwise you are introducing confusion.

The way to read "last-level to the next level" should be the same as "last-level to the sensor".  Thus it should be a unity matrix at every frequency.  Just looking at the code, this seems to be exactly what's happening.  Are you truly not seeing ones there on the diagonals in whatever setup caused you to report this 'bug'?

You are right, though, that you also need a special condition in the conversion loop to make it work. Otherwise the 'fix' would fail.
