### ISSUE TITLE
 NameError: name '__file__' is not defined

### ISSUE THREAD

**Issue by mesghohestany** [atmtools/arts#396]
**Describe the bug**
A bug in pyart when running ycalc.py with jupyter editor:

NameError                                 Traceback (most recent call last)
/tmp/ipykernel_14691/1638470026.py in <module>
     10 import numpy as np
     11 
---> 12 testdir = os.path.dirname(__file__)
     13 
     14 arts = pyarts.workspace.Workspace()

NameError: name '__file__' is not defined

**To Solve**
import os
cwd = os.getcwd()

?

Why does this error happen?

**Comment by simonpf** [comment]
``__file__`` is a special variable that contains the filename of the current module. However, it is only defined when a module is imported not when a source file is executed interactively in IPython. So while this file is  not meant to be executed interactively, you can work around it by simply defining ``__file__ = "."`` in your current session before loading source code.

Anyways, this is expected behavior of Python and doesn't have much to do with ``pyarts``.
