### ISSUE TITLE
Move agenda initialization from agendas.arts into ARTS WSMs

### ISSUE THREAD

**Issue by olemke** [atmtools/arts#503]
This is the plan discussed in the ARTS VidCon (26.08.) to refactor the initialization of agendas:

- Implement one Set function per agenda with an `option` GIN for the choice of initialization (e.g. iy_main_agendaSet with options Emission, Clearsky...)
	- Options should reflect the choices of __ alternatives (e.g. `iy_main_agenda__Emission`) currently in `agendas.arts`
	- One of these options can be set as the default GIN value
	- Built-in documentation must show the contents of the agenda
- Implement new WSM that sets agendas that are currently directly initialized in `agendas.arts` to their defaults (`water_p_eq_agenda`, `gas_scattering_agenda`, `geo_pos_agenda`)
	- This method should call the Set functions of these agendas purely relying on their default option
- Initial implementation should cover everything that is currently set in `agendas.arts`
- Remove `agendas.arts`

**Comment by stefanbuehler** [comment]
Excellent summary.

**Comment by riclarsson** [comment]
This is done with #507 . I ended up removing all of `general/` in the end.

For Agendas the methods look like this: [surface_rtprop_agendaSet](https://atmtools.github.io/arts-docs-master/docserver/methods/surface_rtprop_agendaSet.html).  Each workspace agenda has a set method, and this is enforced by testing.  The same testing also enforce that every default option produces a checked agenda, and that the documentation for that option exist, as in the link above.

For setting a planet, the method is: [PlanetSet](https://atmtools.github.io/arts-docs-master/docserver/methods/PlanetSet.html).  Note that [isotopologue_ratios](https://atmtools.github.io/arts-docs-master/docserver/variables/isotopologue_ratios.html) have to now be set manually because the planet settings often took a file name.  I find this acceptable, but I wonder if we should set it automatically on start-up to the value offered by [isotopologue_ratiosInitFromBuiltin](https://atmtools.github.io/arts-docs-master/docserver/methods/isotopologue_ratiosInitFromBuiltin.html)?

For initializing the legacy continua, the method is: [LegacyContinuaInit](https://atmtools.github.io/arts-docs-master/docserver/methods/LegacyContinuaInit.html)

To add a new Agenda to the workspace after this commit, you have to:
1. Name the agenda, for this example I will call it `example_agenda`
2. Add `example_agenda` in agendas.cc and specify its outputs and intended use
3. Add `example_agenda` in workspace.cc and specify its purpose
4. Add `example_agendaSet` in methods.cc and specify its options in the documentation.  It's output should be only `example_agenda` and its generic input should be only `option`.  It is up to you how to set the generic input default.
5. Add `ENUMCLASS(example_agendaDefaultOptions, char, ...)` or `ENUMCLASS_EMPTY(example_agendaDefaultOptions, char)` to arts_options.h.
6. Add `DeclareOption(Options, example_agendaDefaultOptions)` to py_options.cpp.
7. Add 
```cpp
void example_agendaSet(Workspace& ws,
                       Agenda& out,
                       const String& option,
                       const Verbosity&) {
  out = get_example_agenda(ws, option);
}
```
7. (cont) to m_agenda_set.cc
8. Add `Agenda get_example_agenda(Workspace& ws, const String& option);` to agenda_set.h.
9. Add 
```cpp
Agenda get_example_agenda(Workspace& ws, const String& option) {
  AgendaCreator agenda(ws, "example_agenda");

  using enum Options::example_agendaDefaultOptions;
  switch (Options::toexample_agendaDefaultOptionsOrThrow(option)) {
    case ...:
      ...
      break;
    case FINAL:
      break;
  }
  
  return agenda.finalize();
}
```
9. (cont) to agenda_set.cc.

That should be it, I think.

To add a new option to your new `example_agenda`, you need to do these steps:
1. Modify the `ENUMCLASS(example_agendaDefaultOptions, char, ...)` to read `ENUMCLASS(example_agendaDefaultOptions, char, ..., MyNewOption)` or modify `ENUMCLASS_EMPTY(example_agendaDefaultOptions, char)` to read `ENUMCLASS(example_agendaDefaultOptions, char, MyNewOption)` in arts_options.h.
2. Modify the documentation of `example_agendaSet` in methods.cc to add `MyNewOption:` and describe what the new option is doing.
3. Add the option in the case-list of the `Agenda get_example_agenda(Workspace& ws, const String& option)` in agenda_set.cc

In agenda_set.cc is where the agendas are set.  You can add methods to an agenda using one of these methods:
1. Add a method with all inputs known like: `agenda.add("method_name");`.  This is equivalent to `ws.method_name()` in python.
2. Add a method with some positional inputs known like: `agenda.add("method_name", "variable_name");`.  This is equivalent to `ws.method_name(ws.variable_name)` in python.
3. Add a method with some named inputs like: `agenda.add("method_name", "variable_name=other_variable_name");`.  This is equivalent to `ws.method_name(ws.variable_name=ws.other_variable_name)` in python.
4. Add a method with some value input like: `agenda.add("method_name", Vector{});`.  This is equivalent to `ws.method_name(pyarts.arts.Vector([]))` in python.
5. Add a method with some named value input like:  `agenda.add("method_name", SetWsv{"variable_name", String{}});`.  This is equivalent to `ws.method_name(variable_name=pyarts.arts.String(""))` in python.
6. Set a workspace variable like: `agenda.set("variable_name", Index{0});`.  This is equivalent to `ws.IndexSet(ws.variable_name, 0)` in python.
7. Ignore a workspace variable like: `agenda.ignore("variable_name");`.  This is equivalent to `ws.Ignore(ws.variable_name)` in python.

Note that you can combine positional and named variable setters as you see fit by just appending more of them in a comma-separated list in the `agenda.set` method call.  Also note that all agenda inputs and outputs that are not used by the call to `agenda.finalize()` are automatically ignored and touched, respectively.  One key exception here are agenda input+outputs.  These are only ignored and/or touched when they are completely unused.  For both `Freqloop` and `ScattMC` options of `iy_main_agendaSet`, these actually only output `diy_dx` instead of modifying it, as the `iy_main_agenda` demands.  So these two options have to manually ignore the input.

@stefanbuehler , @erikssonpatrick , and @olemke , I am hoping you are fine with these changes.  I left one question above I would like some opinion about.  Other than that any opinions on the structure above is also welcome.  I feel this greatly simplify using Arts as we no longer have to rely on a known filesystem.

**Comment by olemke** [comment]
> For setting a planet, the method is: [PlanetSet](https://atmtools.github.io/arts-docs-master/docserver/methods/PlanetSet.html). Note that [isotopologue_ratios](https://atmtools.github.io/arts-docs-master/docserver/variables/isotopologue_ratios.html) have to now be set manually because the planet settings often took a file name. I find this acceptable, but I wonder if we should set it automatically on start-up to the value offered by [isotopologue_ratiosInitFromBuiltin](https://atmtools.github.io/arts-docs-master/docserver/methods/isotopologue_ratiosInitFromBuiltin.html)?

I'd say at least for Earth calling `isotopologue_ratiosInitFromBuiltin` in `SetPlanet` sounds like the right thing to do.

**Comment by riclarsson** [comment]
> I'd say at least for Earth calling `isotopologue_ratiosInitFromBuiltin` in `PlanetSet` sounds like the right thing to do.

We cannot do that because [isotopologue_ratios](https://atmtools.github.io/arts-docs-master/docserver/variables/isotopologue_ratios.html) would then be an output of [PlanetSet](https://atmtools.github.io/arts-docs-master/docserver/methods/PlanetSet.html) which leads it to be initialized.  The default initialization of a [SpeciesIsotopologueRatios](https://atmtools.github.io/arts-docs-master/docserver/groups/SpeciesIsotopologueRatios.html) is the same as what you get from [isotopologue_ratiosInitFromBuiltin](https://atmtools.github.io/arts-docs-master/docserver/methods/isotopologue_ratiosInitFromBuiltin.html), so you could basically just be doing what I said anyways, and set it to a default when Arts starts.

**Comment by riclarsson** [comment]
We could do as we did before in the actual `planet*.arts` files and just assume the files exist.  That way it would be the same as before.  Just that now the paths are hard-coded in Arts instead of in a static `.arts` file.

I prefer not to do that.  I don't like global variables in code, and I think it is especially bad if that global variable is a file that may or may not exist.

**Comment by riclarsson** [comment]
I added two drafts showing these solutions at #517 and #518

**Comment by erikssonpatrick** [comment]
Not sure if I really get what the options are. Anyhow, don't think I have a strong opinion and leave it to you and @stefanbuehler.
