### ISSUE TITLE
Migrate Python interface.

### ISSUE THREAD

**Issue by simonpf** [atmtools/arts#54]

**Comment by simonpf** [comment]
For the integration of the Python interface, I am considering to adapt the parsing of function parameters to the ARTS conventions. If I understand the userguide correctly, they are as
follows:

- Function parameters may be given either using only positional arguments
  or using only named arguments
- If positional arguments are used, not all of them must be given. They are parsed in the order 
  specific output, generic output, specific input, generic input.
- If keywords are given they simply replace the corresponding argument.

However, looking at the parser this seems not to be enforced. When I mix the two, I get
an error for unknown WSV:

`AtmRawRead(t_field_raw, basename = "testdata/tropical" )`

Does anyone have thoughts about to handle this? Should we stick to the either positional or named
arguments rule?

**Comment by simonpf** [comment]
Also: What happend when a WSM has a WSV as output and input? Will the argument be listed twice in the WSM or omitted in the input, i.e.:

`WSM(outandinput, ..., outandinput)`

or

`WSM(outandinput, ...)`

In case of the former should outandinput enforced to be the same?

**Comment by olemke** [comment]
> `WSM(outandinput, ...)`

It will be only listed once like above.

**Comment by olemke** [comment]
> However, looking at the parser the first rule seems not to be enforced. When I mix the two, I get
> an error for unknown WSV:
> 
> `AtmRawRead(t_field_raw, basename = "testdata/tropical" )`

Since the first argument is recognized as positional, it expects only WSV names to follow. Hence, 'basename' is an unknown WSV name. So, it is kind of enforced even though the error message is not perfect. The error message for the opposite case is clearer IIRC.

> Does anyone have thoughts about how to handle this? Should we stick to the either positional or named arguments rule?

I'd vote for keeping the rule. The way the parser currently works is that it determines to use positional or keyword arguments based on the first argument. Allowing both types mixed would need quite some rewrite. Although I see how it would be nice to make it behave more similar to Python.
