### ISSUE TITLE
pyarts 2.6.2 Installation error even though glibc requirement is satisfied

### ISSUE THREAD

**Issue by DonteRW** [atmtools/arts#756]
**Describe the bug**

I am trying to install the latest version of pyarts using conda and I am failing to install it.

I am getting the following error:

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - rttools::pyarts -> libgfortran-ng -> __glibc[version='>=2.17']

Your installed version is: 2.35

**To Reproduce**
Steps to reproduce the behaviour:
1. conda create --name ARTS26 
2. conda activate ARTS26
3. conda install rttools::pyarts

**Expected behavior**
I expected pyarts to install without issues as the glibc on my system (v2.35) satisfies the requirement that __glibc[version='>=2.17']

**System info (please complete the following information):**
 - OS: Ubuntu Linux 
 - Version: Ubuntu 22.04.4 LTS, Release: 22.04, Codename: jammy
 - Arch: x86_64
 - ldd --version:  ldd (Ubuntu GLIBC 2.35-0ubuntu3.6) 2.35

**Comment by olemke** [comment]
This is strange, especially because our conda packages were build on Ubuntu 22.04.4. Are you using [Miniforge3](https://github.com/conda-forge/miniforge?tab=readme-ov-file#miniforge) as your conda distribution? pyarts is based on the `conda-forge` repository. If you're using Anaconda, what happens if you add the `conda-forge` repository to your install command: `conda install -c conda-forge rttools::pyarts`?

**Comment by DonteRW** [comment]
@olemke  Thanks. 

conda install -c conda-forge rttools::pyarts works

**Comment by olemke** [comment]
Great! We will update our documentation to be more clear about Miniforge3.
